$terminal = kitty
$file = nautilus
$menu = fuzzel
$leave = wlogout
$screenshotWindow = hyprshot -m window -o ~/Pictures/Screenshots
$screenshotRegion = hyprshot -m region -o ~/Pictures/Screenshots
$screenshotWholeScreen = hyprshot -m active -m output -o ~/Pictures/Screenshots
$lockScreen = hyprlock
$browser = flatpak run app.zen_browser.zen 
$mail = flatpak run net.thunderbird.Thunderbird 

$mainMod = super

# Sound through pactl
binde = , XF86AudioRaiseVolume, exec, bash -c 'vol=$(pactl get-sink-volume @DEFAULT_SINK@ | awk -F"/" '\''NR==1{gsub(/ /,"",$2); print $2}'\'' | tr -d "%"); vol=${vol:-0}; if [ "$vol" -lt 150 ]; then pactl set-sink-volume @DEFAULT_SINK@ +5%; canberra-gtk-play -i audio-volume-change -d "volume"; fi'
binde = , XF86AudioLowerVolume, exec, bash -c 'pactl set-sink-volume @DEFAULT_SINK@ -5%; canberra-gtk-play -i audio-volume-change -d "volume"'
bind  = , XF86AudioMute,      exec, bash -c 'pactl set-sink-mute @DEFAULT_SINK@ toggle; canberra-gtk-play -i audio-volume-muted -d "volume"'


# Brightness through brightnessctl
bindle = , XF86MonBrightnessUp, exec, brightnessctl set +5%
bindle = , XF86MonBrightnessDown, exec, brightnessctl set 5%-

# Example binds, see https://wiki.hyprland.org/Configuring/Binds/ for more
bind = $mainMod, T, exec, $terminal
bind = $mainMod, B, exec, $browser
bind = $mainMod, E, exec, $file
bind = $mainMod, M, exec, $mail
bind = $mainMod, Q, exec, bash -c 'ADDR=$(hyprctl activewindow -j | jq -r .address); hyprctl dispatch closewindow address:$ADDR'
bind = $mainMod SHIFT, Q, killactive, 
bind = $mainMod, ESCAPE, exit, 
bind = $mainMod, V, togglefloating, 
bindr = $mainMod, SPACE, exec, $menu
bind = $mainMod SHIFT, l, exec, $leave
bind = $mainMod Shift, R, exec, hyprctl reload
bind = , PRINT, exec, $screenshotWindow
bind = SHIFT, PRINT, exec, $screenshotRegion
bind = CTRL SHIFT, PRINT, exec, $screenshotRegion
bind = $mainMod, P, pseudo, # dwindle
bind = $mainMod, F, fullscreen, # dwindle
bind = $mainMod, W, togglegroup, # dwindle

# Move focus with mainMod + arrow keys
bind = $mainMod, h, movefocus, l
bind = $mainMod, l, movefocus, r
bind = $mainMod, k, movefocus, u
bind = $mainMod, j, movefocus, d
bind = $mainMod, RETURN, layoutmsg, swapwithmaster

# Switch workspaces with mainMod + [0-9]
bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod, 6, workspace, 6
bind = $mainMod, 7, workspace, 7
bind = $mainMod, 8, workspace, 8
bind = $mainMod, 9, workspace, 9
bind = $mainMod, 0, workspace, 10

# Move active window to a workspace with mainMod + SHIFT + [0-9]
bind = $mainMod SHIFT, 1, movetoworkspace, 1
bind = $mainMod SHIFT, 2, movetoworkspace, 2
bind = $mainMod SHIFT, 3, movetoworkspace, 3
bind = $mainMod SHIFT, 4, movetoworkspace, 4
bind = $mainMod SHIFT, 5, movetoworkspace, 5
bind = $mainMod SHIFT, 6, movetoworkspace, 6
bind = $mainMod SHIFT, 7, movetoworkspace, 7
bind = $mainMod SHIFT, 8, movetoworkspace, 8
bind = $mainMod SHIFT, 9, movetoworkspace, 9
bind = $mainMod SHIFT, 0, movetoworkspace, 10

# Example special workspace (scratchpad)
bind = $mainMod, S, togglespecialworkspace, magic
bind = $mainMod SHIFT, S, movetoworkspace, special:magic

# Scroll through existing workspaces with mainMod + scroll
bind = $mainMod, mouse_down, workspace, e+1
bind = $mainMod, mouse_up, workspace, e-1

# Move/resize windows with mainMod + LMB/RMB and dragging
bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow

gestures {
    # See https://wiki.hyprland.org/Configuring/Variables/ for more
    gesture = 4, horizontal, workspace
    gesture = 3, pinch, fullscreen
    gesture = 3, swipe, move
}

